# Use root/example as user/password credentials
version: '2.9'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: usermysql
      MARIADB_PASSWORD: cursomysql
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: devcar
    ports:
      - "3306:3306"
    volumes:
      - "./banco:/docker-entrypoint-initdb.d"
    mem_limit: 128M
    mem_reservation: 64M

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    mem_limit: 128M
    mem_reservation: 64M